openapi: 3.0.3
info:
  version: '3.0'
  title: Fyle REST API
  contact:
    name: Integrations
    email: support@fyle.in
servers:
  - url: 'https://accounts.fylehq.com'
    description: Live Server
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
          scopes:
            approver.*: Grant all Approver actions
  schemas:
    '401':
      type: object
      properties:
        message:
          enum:
            - invalid token
          type: string
          description: >
            This error means that the input access token is either not issued by
            Fyle or has expired.

            You need to generate a new access token.
    '403':
      type: object
      properties:
        message:
          enum:
            - Forbidden
          type: string
          description: >
            This error means current user does not have enough permissions to
            perform this operation.
    report_approvals:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              description: |
                Id of a report which is to be approved.   
              example: rphs782hj245
      required:
        - data
tags:
  - name: Reports
    description: |
      These API gives you access to your organisation's expense reports data.
paths:
  /v4/approver/report_approvals:
    post:
      tags:
        - Reports
      summary: Approve a report
      description: |
        It moves the report to the `APPROVED` state.
      operationId: PostReportApprovals
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/report_approvals'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorised request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/403'
