openapi: 3.0.3
info:
  version: '3.0'
  title: Approver APIs
  contact:
    name: Integrations
    email: support@fylehq.com
servers:
  - url: 'https://accounts.fylehq.com'
    description: Live Server
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
          scopes:
            approver.*: Grant all Approver actions
  schemas:
    '401':
      type: object
      properties:
        message:
          enum:
            - invalid token
          type: string
          description: >
            This error means that the input access token is either not issued by
            Fyle or has expired.

            You need to generate a new access token.
    '403':
      type: object
      properties:
        message:
          enum:
            - Forbidden
          type: string
          description: >
            This error means current user does not have enough permissions to
            perform this operation.
    report_approvals:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: |
                  Id of a report which is to be approved.   
                example: rphs782hj245
      required:
        - data
    count:
      description: |
        The total number of objects that can be requested.
      type: integer
      example: 10000
    employee_id:
      type: string
      maxLength: 255
      description: >
        This id prodvided by Fyle to uniquely identify an employee within an
        organization.

        This id is always prefixed with `ou`.
      readOnly: true
      example: outGt9ju6qP
    email:
      type: string
      format: email
      maxLength: 127
      example: john.doe@example.com
      description: >
        An immutable field that represents the email address.

        Must be compliant with <a href="https://www.ietf.org/rfc/rfc822.txt">RFC
        822.</a>
    employee:
      type: object
      description: Details of the employee to whom this object belongs to.
      readOnly: true
      properties:
        user_id:
          type: string
          maxLength: 255
          description: |
            This id helps to identify employees in other organisations.
            It is always prefixed with the string `us`.
            It is unique per email.
          example: usIYTLwzlaGu
        email:
          $ref: '#/components/schemas/email'
        code:
          type: string
          maxLength: 255
          example: E84122
          description: >
            This field refers to any string that the client programs can use to
            refer to an employee's unique id.

            This could be any field such as an UUID from an Active Directory
            server or employee id in a HRMS system.
        location:
          type: string
          maxLength: 255
          example: Bangalore Ofc
        level_id:
          type: string
          maxLength: 255
          example: lvlnvJUe9k6Vx
        department_id:
          type: string
          maxLength: 255
          example: dept9in4oIHpdR
        business_unit:
          type: string
          maxLength: 255
          example: Finance ops
          description: >-
            Represents the business unit of the organization to which of the
            employee belongs.
        title:
          type: string
          maxLength: 255
          example: Branch Manager
          description: Represents the title/desgination of the employee.
        mobile:
          type: string
          description: >
            Mobile number of the employee.

            `Given example is a fake number. We don't know who might answer your
            call.`
          example: +1-202-555-0167
        joined_at:
          type: string
          format: date
          example: '2018-10-31'
          description: Date string in YYYY-MM-DD format
        full_name:
          type: string
          maxLength: 255
          example: John Doe
          description: >-
            Represents the full name of the employee. Must be at least 3
            characters.
    created_at:
      type: string
      format: date-time
      description: >
        <a href='https://tools.ietf.org/html/rfc3339#section-5.6'>RFC 3339,
        section 5.6 compliant timestamp.</a>

        Signifies when this object was created.
      readOnly: true
      example: '2020-06-01T13:14:54.804Z'
    updated_at:
      type: string
      format: date-time
      description: >
        <a href='https://tools.ietf.org/html/rfc3339#section-5.6'>RFC 3339,
        section 5.6 compliant timestamp.</a>

        Signifies when this object was updated.
      readOnly: true
      example: '2020-06-11T13:14:55.201598Z'
    currency:
      type: string
      maxLength: 10
      description: >
        The three-letter currency code following ISO standard <a
        href='https://www.iso.org/iso-4217-currency-codes.html'>ISO 4217</a>
      example: USD
    amount:
      type: integer
      description: |
        Amount value of the object.
      example: 100
    creator_id:
      type: string
      maxLength: 255
      description: >
        An unique ID, generated by Fyle, for identifying the Employee who
        created the object. Once an object is created, the value of this field
        cannot be changed and is immutable.<br>
      example: ou12345Zdfx
      readOnly: true
    location:
      type: object
      properties:
        city:
          type: string
          example: London
        state:
          type: string
          example: London
        display_name:
          type: string
        country:
          type: string
          example: United Kingdom
        formatted_address:
          type: string
          example: '221 Baker St, Marylebone, London, United Kingdom'
        latitude:
          type: number
          example: 12.971599
        longitude:
          type: number
          example: 77.594566
    approvals:
      type: object
      description: |
        siginifies all the approvals of a particular object.
      properties:
        approver_id:
          type: string
        state:
          type: string
          enum:
            - APPROVED
            - APPROVAL_PENDING
            - APPROVAL_DISABLED
      example:
        approver_id: oueoblnegf
        state: APPROVED
    org_id:
      type: string
      description: |
        The unique id of the Organization to which the object is associated.
      example: orwruogwnngg
    reports:
      type: object
      properties:
        id:
          type: string
          maxLength: 255
          description: |
            This id prodvided by Fyle to uniquely identify a Expense report.
            This id is always prefixed with `rp`.
          readOnly: true
          example: rpevetgn3kl
        employee_id:
          $ref: '#/components/schemas/employee_id'
        employee:
          $ref: '#/components/schemas/employee'
        created_at:
          $ref: '#/components/schemas/created_at'
        updated_at:
          $ref: '#/components/schemas/updated_at'
        submitted_at:
          type: string
          format: date-time
          description: >
            RFC 3339, section 5.6
            "https://tools.ietf.org/html/rfc3339#section-5.6" compliant
            timestamp on which the Report was submitted to the Approvers.

            If the Report is not yet submitted, this could be null. <br>
          readOnly: true
        purpose:
          type: string
        claim_number:
          type: string
          maxLength: 255
        currency:
          $ref: '#/components/schemas/currency'
        amount:
          $ref: '#/components/schemas/amount'
        tax:
          type: number
        state:
          type: string
        source:
          type: string
        approved_at:
          type: string
          format: date-time
          description: >
            RFC 3339, section 5.6
            "https://tools.ietf.org/html/rfc3339#section-5.6" compliant
            timestamp on which the Report was approved. This field could be null
            if the Report was not yet approved.
          readOnly: true
        verified:
          type: boolean
          description: |
            Indicates whether the Report is verified or not.
          readOnly: true
        verified_at:
          type: string
          format: date-time
          description: >
            RFC 3339, section 5.6
            "https://tools.ietf.org/html/rfc3339#section-5.6" compliant
            timestamp on which the Report was verified. If the Report is not
            verified yet, this could be null.
          readOnly: true
        reimbursed_at:
          type: string
          format: date-time
          description: >
            RFC 3339, section 5.6
            "https://tools.ietf.org/html/rfc3339#section-5.6" compliant
            timestamp on which the Report was Reimbursed. If the Report is not
            reimbursed or submitted yet, this could be null.
          readOnly: true
        settlement_id:
          type: string
          readOnly: true
          maxLength: 255
          description: >
            An unique ID, generated by Fyle, for identifying the Settlement.
            Once a Report is paid, the value of this field cannot be changed and
            is immutable. <br>
          example: setzS7mbPKPWg
        settled_at:
          readOnly: true
          type: string
          format: date-time
          description: >
            RFC 3339, section 5.6
            "https://tools.ietf.org/html/rfc3339#section-5.6" compliant
            timestamp on which the report was settled. <br>
          example: '2017-07-21T17:32:28Z'
        num_expenses:
          type: integer
        expense_ids:
          type: array
          items:
            type: string
        verification_state:
          type: string
        creator_id:
          $ref: '#/components/schemas/creator_id'
        creator:
          allOf:
            - $ref: '#/components/schemas/employee'
          description: |
            Details of employee who created this report.
        trip_request_id:
          type: string
        physical_bill:
          type: boolean
        physical_bill_at:
          type: string
        manual_flag:
          type: boolean
        policy_flag:
          type: boolean
        type:
          type: string
        started_at:
          type: string
        ended_at:
          type: string
        locations:
          type: array
          items:
            $ref: '#/components/schemas/location'
        report_approvals:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/approvals'
              - type: object
                properties:
                  rank:
                    type: integer
                    example: 1
        org_id:
          $ref: '#/components/schemas/org_id'
    post_report_approvals:
      type: object
      properties:
        count:
          $ref: '#/components/schemas/count'
        url:
          type: string
          example: /common/report_approvals
        data:
          type: array
          items:
            $ref: '#/components/schemas/reports'
      required:
        - data
tags:
  - name: Reports
    description: |
      These API gives you access to your organisation's expense reports data.
paths:
  /approver/report_approvals:
    post:
      tags:
        - Reports
      summary: Approve reports
      description: |
        It approve expense reports.
      operationId: PostReportApprovals
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/report_approvals'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    example: /common/report_approvals
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/post_report_approvals'
        '401':
          description: Unauthorised request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/403'
