openapi: 3.0.3
info:
  version: '3.0'
  title: Approver APIs
  contact:
    name: Integrations
    email: support@fylehq.com
servers:
  - url: 'https://accounts.fylehq.com'
    description: Live Server

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
          scopes:
            approver.*: Grant all Approver actions

tags:
  - name: Reports
    description: |
      These API gives you access to your organisation's expense reports data.

paths:
  /approver/report_approvals:
    $ref: 'paths/report_approvals.yaml'